.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_000.csv --deg 0.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_010.csv --deg 10.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_020.csv --deg 20.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_030.csv --deg 30.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_040.csv --deg 40.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_050.csv --deg 50.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_060.csv --deg 60.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_070.csv --deg 70.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_080.csv --deg 80.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_090.csv --deg 90.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_100.csv --deg 100.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_110.csv --deg 110.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_120.csv --deg 120.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_130.csv --deg 130.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_140.csv --deg 140.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_150.csv --deg 150.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_160.csv --deg 160.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_170.csv --deg 170.0
.\.venv\Scripts\python .\experiments\generate_rotations.py -i .\dataset\ModelNet40 -c .\experiments\sampledata\modelnet40_half1.txt --format wt -o .\results\ex1\gt\pert_180.csv --deg 180.0